version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      USER_APP_MONGO_USER: ${USER_APP_MONGO_USER}
      USER_APP_MONGO_PASSWORD: ${USER_APP_MONGO_PASSWORD}
      GUIDE_APP_MONGO_USER: ${GUIDE_APP_MONGO_USER}
      GUIDE_APP_MONGO_PASSWORD: ${GUIDE_APP_MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --auth
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
